name: NewAmazingLuckyBlocks
main: me.i2000c.newalb.NewAmazingLuckyBlocks
version: 3.3.3-OutcomePacks-bug-fix_39
description: A new incredible LuckyBlock plugin
author: I2000C
commands:
   alb:
        description: The main command of New Amazing Lucky Blocks.
   nalb:
        description: The main command of New Amazing Lucky Blocks.
softdepend: [WorldEdit]
api-version: 1.13
